add summary to clang-tidy too
Signed-off-by: M. Fatih Cırıt <mfc@autoware.org>

diff --git a/.github/workflows/build-test-tidy-pr.yaml b/.github/workflows/build-test-tidy-pr.yaml
--- a/.github/workflows/build-test-tidy-pr.yaml
+++ b/.github/workflows/build-test-tidy-pr.yaml
@@ -18,36 +18,6 @@ jobs:
     with:
       label: run:build-and-test-differential
 
-  require-label-test:
-    needs:
-      - require-label
-    if: ${{ always() }}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Initialize Summary
-        run: echo "### Build Test PR Results" > $GITHUB_STEP_SUMMARY
-        shell: bash
-
-      - name: Evaluate build-and-test-differential
-        id: eval_diff
-        uses: ./.github/actions/evaluate-job-result
-        with:
-          job_result: ${{ needs.require-label.result }}
-          job_name: require-label
-          expected_results: success
-
-      - name: Final Status
-        run: |
-          if [[ "${{ steps.eval_diff.outputs.failed }}" == "true" || "${{ steps.eval_cuda.outputs.failed }}" == "true" ]]; then
-            echo "Some checks failed. ❌"
-            exit 1
-          else
-            echo "::notice::All checks passed successfully! ✅"
-          fi
-        shell: bash
-
   check-if-cuda-job-is-needed:
     needs: require-label
     runs-on: ubuntu-latest
@@ -151,9 +121,25 @@ jobs:
     if: ${{ always() }}
     runs-on: ubuntu-latest
     steps:
+      - name: Initialize Summary
+        run: echo "### Clang Tidy PR Results" > $GITHUB_STEP_SUMMARY
+        shell: bash
+
       - name: Check clang-tidy success
         if: ${{ needs.clang-tidy-differential.result == 'success' || needs.clang-tidy-differential-cuda.result == 'success' }}
-        run: echo "clang-tidy-pr succeeded."
+        run: |
+          echo "All checks passed successfully! ✅"
+          echo "All checks passed successfully! ✅" >> $GITHUB_STEP_SUMMARY
+
       - name: Fail if conditions not met
         if: ${{ !(needs.clang-tidy-differential.result == 'success' || needs.clang-tidy-differential-cuda.result == 'success') }}
-        run: exit 1
+        run: |
+          echo "::error::❌ Either one of the following should have succeeded:"
+          echo "::error::clang-tidy-differential: ${{ needs.clang-tidy-differential.result }}"
+          echo "::error::clang-tidy-differential-cuda: ${{ needs.clang-tidy-differential-cuda.result }}"
+          
+          echo "❌ Either one of the following should have succeeded:" >> $GITHUB_STEP_SUMMARY
+          echo "clang-tidy-differential: ${{ needs.clang-tidy-differential.result }}" >> $GITHUB_STEP_SUMMARY
+          echo "clang-tidy-differential-cuda: ${{ needs.clang-tidy-differential-cuda.result }}" >> $GITHUB_STEP_SUMMARY
+
+          exit 1
